name: CI

on: [push, pull_request]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout zoridor
        uses: actions/checkout@v2
        with:
          path: zoridor
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Build test
        run: zig build test
        working-directory: zoridor
      - name: Build terminal
        run: zig build -Dweb=false
        working-directory: zoridor
      - name: Build web
        run: zig build -Dweb=true
        working-directory: zoridor
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v3
      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "zoridor/zig-out"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

