name: CI

on: [push, pull_request]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout zoridor
        uses: actions/checkout@v2
        with:
          path: zoridor
      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: master
      - name: Build cart
        run: zig build
        working-directory: zoridor

